### ISSUE TITLE
Recieved bytes not logged, not displayed

### ISSUE THREAD

**Issue by iehgit** [maybe-hello-world/fbs#2]
I am able to pair, connect, and send some bytes, and the log shows that bytes have been received. But the app does not log and not display the data. Debug Logging has been enabled.

Debug Log:
93136002 [I][FapLoader] FAP Loader is loading /ext/apps/Misc_Extra/fbs.fap
93136040 [I][FapLoader] FAP Loader is mapping
93136098 [I][elf] Total size of loaded sections: 982
93136100 [I][FapLoader] Loaded in 98ms
93136102 [I][FapLoader] FAP Loader is starting app
93136105 [D][FlipperBTSerial] BT is working, hijacking the serial connection...
93154298 [D][BtGap] set_non_discoverable success
93194689 [I][BtGap] Connection parameters: Connection Interval: 36 (45 ms), Slave Latency: 0, Supervision Timeout: 42
93194796 [D][BtGap] Slave security initiated
93195155 [I][BtGap] Pairing complete
93195160 [I][BtSrv] Open RPC connection
93195163 [D][RpcSrv] Session started
93195166 [D][BtBatterySvc] Updating battery level characteristic
93195872 [D][BtSerialSvc] Received 14 bytes
93195874 [D][BtSerialSvc] Available buff size: 1010
93200056 [I][BtGap] Disconnect from client. Reason: 13
93200061 [I][BtSrv] Close RPC connection
93200064 [D][RpcSrv] Session terminated

Sent bytes:
Hello, world!\n

Python script used to send:
```
import time
from gattlib import GATTRequester, GATTResponse

DEVICE_MAC_ADDRESS = "80:E1:27:9F:BD:5A"
TX_UUID = "19ed82ae-ed21-4c9d-4145-228e62fe0000"
RX_UUID = "19ed82ae-ed21-4c9d-4145-228e61fe0000"

class BluetoothSerial:
    def __init__(self, device_mac_address):
        self.req = GATTRequester(device_mac_address, False)
        self.tx_handle = None
        self.rx_handle = None

    def connect(self):
        self.req.connect(True)  # True to use a random address
        if self.req.is_connected():
            print("Connected to", DEVICE_MAC_ADDRESS)
            self.find_handles()
        else:
            print("Failed to connect to", DEVICE_MAC_ADDRESS)

    def find_handles(self):
        characteristics = self.req.discover_characteristics()
        for char in characteristics:
            if char['uuid'] == TX_UUID:
                self.tx_handle = char['value_handle']
            if char['uuid'] == RX_UUID:
                self.rx_handle = char['value_handle']

        if self.tx_handle is None or self.rx_handle is None:
            print("Failed to find handles for TX and/or RX characteristics.")
            return False
        return True

    def write_data(self, data):
        if self.tx_handle is not None:
            self.req.write_by_handle(self.tx_handle, data)
            print("Data written:", data)
        else:
            print("TX handle not found. Unable to write data.")

    def read_data(self):
        if self.rx_handle is not None:
            data = self.req.read_by_handle(self.rx_handle)
            return data
        else:
            print("RX handle not found. Unable to read data.")
            return None

def main():
    bt_serial = BluetoothSerial(DEVICE_MAC_ADDRESS)
    bt_serial.connect()

    # Transmit data to the Bluetooth device
    data = b'Hello, world!\n'
    bt_serial.write_data(data)

    # Read data from the Bluetooth device
    received_data = bt_serial.read_data()
    print("Received data:", received_data)

if __name__ == "__main__":
    main()
```

**Comment by maybe-hello-world** [comment]
Hi, I'll return to this in a couple of days. Thank you for providing the information :)

**Comment by iehgit** [comment]
Hi, it seems like the right things have been happening, just not at the right time in the right order.
Got it to work (albeit not beautifully) by sending the message repeatedly in a loop, and copying the mechanism from your flipper-bp fap, which re-inits the receiving part on a button press of the OK-button,  in this fap. After mashing the button a bit, the recieved bytes get printed to the log indeed.

**Comment by maybe-hello-world** [comment]
Oh, I see. Thank you anyway, there's definitely a room to improve things ^^
