### ISSUE TITLE
Den slukker og reboter 

### ISSUE THREAD

**Issue by lassie666** [maybe-hello-world/fbs#3]
Hver gang jeg prøver så slukker den ned lige med det samme

**Comment by maybe-hello-world** [comment]
have you turned on Bluetooth? Do you see anything in the logs of the flipper?

**Comment by lassie666** [comment]
Nej det havde jeg slået fra.  Jeg troede det måske var fordi det var slået fra.    Men det ka jeg høre jeg at jeg gjorde rigtig ... så ved jeg slet ik hva det er

**Comment by maybe-hello-world** [comment]
Please, set the log level to Debug, collect logs from Flipper with fbt cli -> log, and attach them to this issue. Currently, without logs, I cannot predict what could be the problem :D

**Comment by maybe-hello-world** [comment]
Closing this issue, as I guess no help is needed anymore. Feel free to reopen.
