### ISSUE TITLE
How to connect it?

### ISSUE THREAD

**Issue by gugo2808** [maybe-hello-world/fbs#4]
I tried to install the app. The app didn't crash, so that cool.
But I can't understand, how to use it). 
I can't connect it with my phone, because it tells me that the app is needed. 
When I connect before launching flipper app with original app on my phone and than launch an app, Bluetooth disables, and I still can't connect it. 

I wanted to use it in my project with my android application, because the original connection I didn't really understood. 

Thank you!

**Comment by maybe-hello-world** [comment]
Hello,
The app isn't supposed to be just used alone, with a mobile phone, or any official flipper app; it's a template for your possible apps.
You can read the readme in the repo to get it working (you need a CLI connection to the flipper and Bluetooth on your PC, Linux preferred, together with Bluetooth-controlling terminal apps like bluetoothctl).

**Comment by gugo2808** [comment]
I was trying to build Flipper BP app too. 
In Readme is written: establish Bluetooth connection. 
I can't understand how. My Mac doesn't see any device in Bluetooth.
In flipper logs is written, that: 
"""Bt is working, hijacking the serial connection"""

When I try to connect it with phone, I get, an application is needed to connect it. 

I can't understand how to send bytes via channel. 

Need your help)!. Please). 

Thank you!

**Comment by maybe-hello-world** [comment]
Better start connecting from the PC to get it working. ^^

Set flipper to debug, set the log level to debug, and start logs on flipper in CLI.
Then use any BLE app to connect and send some bytes.
E.g., with bluetoothctl you need to turn `scan on`, find the flipper, `connect <flipper BT MAC address>`, then `menu gatt`, and then select the tx attribute and write there some bytes. probably somewhere in the middle, you'll need to pair the flipper also.

If everything's done correctly, you'll see these bytes in the debug log of the flipper - it's the app caught and printed them. You can do the same from the android app, you need to connect to the flipper (+pair) and write bytes to tx channel (see readme). Don't forget to listen to logs on the flipper's side.

**Comment by gugo2808** [comment]
Oh god). Thanks). 
Made it with an android phone). 
Find just a simple android ble serial communication app. 
1000 thanks, and I learned bunch of new stuff. 
🤘✌️.

**Comment by maybe-hello-world** [comment]
Congrats! ^^
I'll close this issue as completed, feel free to contact me again if needed.
